### ISSUE TITLE
Tracking Issue for Begginers

### ISSUE THREAD

**Issue by PhiSyX** [PhiSyX/cfoulatech#1]
# HTML / CSS

- [x] La Syntaxe 
- [x] Les Layers
- [x] Les sélecteurs
- [x] Les propriétés
- [x] Les couleurs
- [x] Le Box Model
- [x] Images
- [x] Les positions
- [ ] z-index
- [x] Float
- [ ] Flex
- [ ] Grid
- [ ] ...

# JavaScript

- [x] Les variables
- [x] Les constantes
- [x] Les types
- [x] Les opérateurs arithmétiques / logiques / comparaisons
- [x] Les structures de contrôle
- [x] Les conditions (+ ternaires) / switch
- [x] Les boucles
- [ ] ...

# PHP

- [x] Les variables
- [x] Les types
- [x] Les opérateurs arithmétiques / logiques / comparaisons
- [x] Les structures de contrôle
- [x] Les conditions (+ ternaires) / switch
- [x] Les boucles
- [ ] ...

# MySQL

- [x] Création base de données
- [x] Suppression base de données
- [x] Création table
- [x] Les types
- [x] Suppression table
- [x] Modification table (ajout colonne, modification colonne, suppression colonne)
- [x] Les clés
- [x] Requête d'insertion (INSERT)
- [x] Requête de suppression (DELETE / TRUNCATE)
- [x] Requête de modification (UPDATE)
- [x] Requête de sélection (SELECT)
- [x] Les conditions
- [X] Les opérateurs
- [ ] ...

**Comment by PhiSyX** [comment]
Il y a plusieurs façons de créer du code.

Jusqu'à maintenant, on a vu 3 manières de faire, c'est-à-dire qu'on a vu la méthode impérative où en fait, l'idée c'est d'avoir une série d'instructions à exécuter dans un ordre précis.

Par exemple : déclaration de variables, modification de variables, appelle de
fonction (echo, alert, ...), boucles

Ensuite, on a vu la méthode procédurale (ou fonctionnelle) qui consiste à reproduire tout ce qu'on a déjà vu avec la méthode impérative, mais à l'intérieur de fonctions afin que le code soit plus clair à lire. Afin de ne pas dupliquer certaine partie de logique, si jamais on doit exécuter ces fonctions à
différent endroit du code, dans le but d'avoir un résultat le plus indépendant ou le plus générique en rapport aux paramètres de fonctions.

Ensuite, on a vu la méthode objet qui va consister à regrouper des variables (propriétés) et des fonctions (méthodes) liées à un objet. 

Par exemple : on ne veut pas que les variables/fonctions liées à un produit,
se retrouvent dans l'objet utilisateur, et inversement.
