### ISSUE TITLE
Tracking Issue for `PHP`. Beginners Section.

### ISSUE THREAD

**Issue by PhiSyX** [PhiSyX/cfoulatech#3]
# PHP

- [x] Les variables
  - [x] L'initialisation
  - [x] L'affectation
- [x] Les types
  - [x] `bool`
  - [x] `string
  - [x] `int`
  - [x] `array` tableau indexée       (simple liste)
  - [x] `array` tableau clé => valeur (dictionnaire)
- [x] Les opérateurs arithmétiques / logiques / comparaisons
  - [x] Introduction de tous les opérateeurs
  - [x] Différence double / triple (in)égalité
- [x] Les structures de contrôle
  - [x] `if`
  - [x] `switch`
  - [x] `ternaire`
- [x] Les boucles
  - [x] `while`
  - [x] `for` classique, avec un compteur
  - [x] `foreach`
- [x] Les fonctions
  - [x] Fonctions built-in
  - [x] Fonctions utilisateur
  - [x] Typage des paramètres
  - [x] Typage du retour
- [x] Inclusion de fichiers
- [x] PHP x HTML
- [ ] ...
