### ISSUE TITLE
Tracking Issue for `MySQL`. Beginners Section.

### ISSUE THREAD

**Issue by PhiSyX** [PhiSyX/cfoulatech#4]
# MySQL

- [x] Création base de données
- [x] Suppression base de données
- [x] Création table
- [x] Les types
- [x] Suppression table
- [x] Modification table (ajout colonne, modification colonne, suppression colonne)
- [x] Les clés
- [x] Requête d'insertion (INSERT)
- [x] Requête de suppression (DELETE / TRUNCATE)
- [x] Requête de modification (UPDATE)
- [x] Requête de sélection (SELECT)
- [x] Les conditions
- [x] Les opérateurs
  - [x] comparaisons, logiques
  - [x] LIKE
  - [x] IN
  - [x] BETWEEN
- [x] Les fonctions built-in
  - [x] CONCAT
  - [x] LENGTH
  - [x] LOWER
  - [x] REPLACE
  - [x] SUBSTR
  - [x] UPPER
- [x] Les dates
  - [x] DATE_ADD, DATE_SUB, DATE_FORMAT
  - [x] DAY, MONTH, YEAR
- [ ] ...
